sensors:
  luftdaten:
    7675:
      name: St Werburghs - The Yard north
      start_date: 2017-12-10
      location:
        latitude: 51.474708
        longitude: -2.576841

    7677:
      name: St Werburghs - The Yard
      start_date: 2017-12-11
      location:
        latitude: 51.474708
        longitude: -2.576841

    17502:
      name: St Werberghs Community Centre
      start_date: 2018-10-14
      location:
        latitude: 51.468
        longitude: -2.5718
#
#    7685:
#      name: St Werburghs 2
#      start_date: 2017-12-11
#      location:
#        latitude: 51.474708
#        longitude: -2.576841
